spring:
  application:
    name: stream-kafka
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: 192.168.1.110
          brokers: 192.168.1.110
      bindings:
        output:
          destination: stream-kafka-1
          content-type: application/json
      default-binder: kafka
