spring:
  application.name: config-server
  cloud:
    config:
      server:
        native:
          # 不能放在classpath下，否则 config-server /bus/refresh不会刷新
          search-locations: D:/d_backup/github/java-demos-segment/springcloud-learning/springcloud-config-server/properties
    stream:
      kafka:
        binder:
          zkNodes: 10.174.20.33
          brokers: 10.174.20.33
server:
  port: 9001

management:
  security:
    enabled: false
