spring:
  application.name: config-server
  profiles:
      active: native
  cloud:
      config:
        server:
          native:
            search-locations: classpath:properties/
server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/